
module Keymap.CustomDvorak
    ( customDvorakKeymap
    ) where

import State
import qualified Data.Vector as V

customDvorakKeymap :: V.Vector (V.Vector KeySymbol)
customDvorakKeymap =  [
     (9, group [          XK_Escape ])
    ,(10, group [               XK_1,          XK_exclam ])
    ,(11, group [               XK_2,              XK_at ])
    ,(12, group [               XK_3,      XK_numbersign ])
    ,(13, group [               XK_4,          XK_dollar ])
    ,(14, group [               XK_5,         XK_percent ])
    ,(15, group [               XK_6,     XK_asciicircum, XK_dead_circumflex, XK_dead_circumflex ])
    ,(16, group [               XK_7,       XK_ampersand ])
    ,(17, group [               XK_8,        XK_asterisk ])
    ,(18, group [               XK_9,       XK_parenleft,      XK_dead_grave,        XK_NoSymbol ])
    ,(19, group [               XK_0,      XK_parenright ])
    ,(20, group [     XK_bracketleft,       XK_braceleft ])
    ,(21, group [    XK_bracketright,      XK_braceright,      XK_dead_tilde,        XK_NoSymbol ])
    ,(22, group [       XK_BackSpace,       XK_BackSpace,        XK_NoSymbol,        XK_NoSymbol, XK_Terminate_Server ])
    ,(23, group [             XK_Tab,    XK_ISO_Left_Tab ])
    ,(24, group [      XK_apostrophe,        XK_quotedbl,      XK_dead_acute,  XK_dead_diaeresis ])
    ,(25, group [           XK_comma,            XK_less,    XK_dead_cedilla,      XK_dead_caron ])
    ,(26, group [          XK_period,         XK_greater,   XK_dead_abovedot,  XK_periodcentered ])
    ,(27, group [               XK_p,               XK_P ])
    ,(28, group [               XK_y,               XK_Y ])
    ,(29, group [               XK_f,               XK_F ])
    ,(30, group [               XK_g,               XK_G ])
    ,(31, group [               XK_c,               XK_C ])
    ,(32, group [               XK_r,               XK_R ])
    ,(33, group [               XK_l,               XK_L ])
    ,(34, group [           XK_slash,        XK_question ])
    ,(35, group [           XK_equal,            XK_plus ])
    ,(36, group [          XK_Return ])
    ,(37, group [       XK_Caps_Lock ])
    ,(38, group [               XK_a,               XK_A ])
    ,(39, group [               XK_o,               XK_O ])
    ,(40, group [               XK_e,               XK_E ])
    ,(41, group [               XK_i,               XK_I ])
    ,(42, group [               XK_u,               XK_U ])
    ,(43, group [               XK_d,               XK_D ])
    ,(44, group [               XK_h,               XK_H ])
    ,(45, group [               XK_t,               XK_T ])
    ,(46, group [               XK_n,               XK_N ])
    ,(47, group [               XK_s,               XK_S ])
    ,(48, group [           XK_minus,      XK_underscore ])
    ,(49, group [           XK_grave,      XK_asciitilde,      XK_dead_grave,      XK_dead_tilde ])
    ,(50, group [         XK_Shift_L ])
    ,(51, group [       XK_backslash,             XK_bar ])
    ,(52, group [           XK_colon,       XK_semicolon,     XK_dead_ogonek, XK_dead_doubleacute ])
    ,(53, group [               XK_q,               XK_Q ])
    ,(54, group [               XK_j,               XK_J ])
    ,(55, group [               XK_k,               XK_K ])
    ,(56, group [               XK_x,               XK_X ])
    ,(57, group [               XK_b,               XK_B ])
    ,(58, group [               XK_m,               XK_M ])
    ,(59, group [               XK_w,               XK_W ])
    ,(60, group [               XK_v,               XK_V ])
    ,(61, group [               XK_z,               XK_Z ])
    ,(62, group [         XK_Shift_R ])
    ,(63, group [     XK_KP_Multiply,     XK_KP_Multiply,     XK_KP_Multiply,     XK_KP_Multiply,   XK_XF86ClearGrab ])
    ,(64, group [          XK_Meta_L,          XK_Meta_L ])
    ,(65, group [           XK_space ])
    ,(66, group [       XK_Control_L ])
    ,(67, group [              XK_F1,              XK_F1,              XK_F1,              XK_F1, XK_XF86Switch_VT_1 ])
    ,(68, group [              XK_F2,              XK_F2,              XK_F2,              XK_F2, XK_XF86Switch_VT_2 ])
    ,(69, group [              XK_F3,              XK_F3,              XK_F3,              XK_F3, XK_XF86Switch_VT_3 ])
    ,(70, group [              XK_F4,              XK_F4,              XK_F4,              XK_F4, XK_XF86Switch_VT_4 ])
    ,(71, group [              XK_F5,              XK_F5,              XK_F5,              XK_F5, XK_XF86Switch_VT_5 ])
    ,(72, group [              XK_F6,              XK_F6,              XK_F6,              XK_F6, XK_XF86Switch_VT_6 ])
    ,(73, group [              XK_F7,              XK_F7,              XK_F7,              XK_F7, XK_XF86Switch_VT_7 ])
    ,(74, group [              XK_F8,              XK_F8,              XK_F8,              XK_F8, XK_XF86Switch_VT_8 ])
    ,(75, group [              XK_F9,              XK_F9,              XK_F9,              XK_F9, XK_XF86Switch_VT_9 ])
    ,(76, group [             XK_F10,             XK_F10,             XK_F10,             XK_F10, XK_XF86Switch_VT_10 ])
    ,(77, group [        XK_Num_Lock ])
    ,(78, group [     XK_Scroll_Lock ])
    ,(79, group [         XK_KP_Home,            XK_KP_7 ])
    ,(80, group [           XK_KP_Up,            XK_KP_8 ])
    ,(81, group [        XK_KP_Prior,            XK_KP_9 ])
    ,(82, group [     XK_KP_Subtract,     XK_KP_Subtract,     XK_KP_Subtract,     XK_KP_Subtract,  XK_XF86Prev_VMode ])
    ,(83, group [         XK_KP_Left,            XK_KP_4 ])
    ,(84, group [        XK_KP_Begin,            XK_KP_5 ])
    ,(85, group [        XK_KP_Right,            XK_KP_6 ])
    ,(86, group [          XK_KP_Add,          XK_KP_Add,          XK_KP_Add,          XK_KP_Add,  XK_XF86Next_VMode ])
    ,(87, group [          XK_KP_End,            XK_KP_1 ])
    ,(88, group [         XK_KP_Down,            XK_KP_2 ])
    ,(89, group [         XK_KP_Next,            XK_KP_3 ])
    ,(90, group [       XK_KP_Insert,            XK_KP_0 ])
    ,(91, group [       XK_KP_Delete,      XK_KP_Decimal ])
    ,(92, group [ XK_ISO_Level3_Shift ])
    ,(94, group [            XK_less,         XK_greater,             XK_bar,       XK_brokenbar ])
    ,(95, group [             XK_F11,             XK_F11,             XK_F11,             XK_F11, XK_XF86Switch_VT_11 ])
    ,(96, group [             XK_F12,             XK_F12,             XK_F12,             XK_F12, XK_XF86Switch_VT_12 ])
    ,(98, group [        XK_Katakana ])
    ,(99, group [        XK_Hiragana ])
    ,(100, group [     XK_Henkan_Mode ])
    ,(101, group [ XK_Hiragana_Katakana ])
    ,(102, group [        XK_Muhenkan ])
    ,(104, group [        XK_KP_Enter ])
    ,(105, group [       XK_Control_R ])
    ,(106, group [       XK_KP_Divide,       XK_KP_Divide,       XK_KP_Divide,       XK_KP_Divide,      XK_XF86Ungrab ])
    ,(107, group [           XK_Print,         XK_Sys_Req ])
    ,(108, group [           XK_Alt_L,           XK_Alt_L ])
    ,(109, group [        XK_Linefeed ])
    ,(110, group [            XK_Home ])
    ,(111, group [              XK_Up ])
    ,(112, group [           XK_Prior ])
    ,(113, group [            XK_Left ])
    ,(114, group [           XK_Right ])
    ,(115, group [             XK_End ])
    ,(116, group [            XK_Down ])
    ,(117, group [            XK_Next ])
    ,(118, group [          XK_Insert ])
    ,(119, group [          XK_Delete ])
    ,(121, group [   XK_XF86AudioMute ])
    ,(122, group [ XK_XF86AudioLowerVolume ])
    ,(123, group [ XK_XF86AudioRaiseVolume ])
    ,(124, group [    XK_XF86PowerOff ])
    ,(125, group [        XK_KP_Equal ])
    ,(126, group [       XK_plusminus ])
    ,(127, group [           XK_Pause,           XK_Break ])
    ,(128, group [     XK_XF86LaunchA ])
    ,(129, group [      XK_KP_Decimal,      XK_KP_Decimal ])
    ,(130, group [          XK_Hangul ])
    ,(131, group [    XK_Hangul_Hanja ])
    ,(133, group [         XK_Super_L ])
    ,(134, group [         XK_Super_R ])
    ,(135, group [            XK_Menu ])
    ,(136, group [          XK_Cancel ])
    ,(137, group [            XK_Redo ])
    ,(138, group [        XK_SunProps ])
    ,(139, group [            XK_Undo ])
    ,(140, group [        XK_SunFront ])
    ,(141, group [        XK_XF86Copy ])
    ,(142, group [        XK_XF86Open ])
    ,(143, group [       XK_XF86Paste ])
    ,(144, group [            XK_Find ])
    ,(145, group [         XK_XF86Cut ])
    ,(146, group [            XK_Help ])
    ,(147, group [      XK_XF86MenuKB ])
    ,(148, group [  XK_XF86Calculator ])
    ,(150, group [       XK_XF86Sleep ])
    ,(151, group [      XK_XF86WakeUp ])
    ,(152, group [    XK_XF86Explorer ])
    ,(153, group [        XK_XF86Send ])
    ,(155, group [        XK_XF86Xfer ])
    ,(156, group [     XK_XF86Launch1 ])
    ,(157, group [     XK_XF86Launch2 ])
    ,(158, group [         XK_XF86WWW ])
    ,(159, group [         XK_XF86DOS ])
    ,(160, group [ XK_XF86ScreenSaver ])
    ,(161, group [ XK_XF86RotateWindows ])
    ,(162, group [    XK_XF86TaskPane ])
    ,(163, group [        XK_XF86Mail ])
    ,(164, group [   XK_XF86Favorites ])
    ,(165, group [  XK_XF86MyComputer ])
    ,(166, group [        XK_XF86Back ])
    ,(167, group [     XK_XF86Forward ])
    ,(169, group [       XK_XF86Eject ])
    ,(170, group [       XK_XF86Eject,       XK_XF86Eject ])
    ,(171, group [   XK_XF86AudioNext ])
    ,(172, group [   XK_XF86AudioPlay,  XK_XF86AudioPause ])
    ,(173, group [   XK_XF86AudioPrev ])
    ,(174, group [   XK_XF86AudioStop,       XK_XF86Eject ])
    ,(175, group [ XK_XF86AudioRecord ])
    ,(176, group [ XK_XF86AudioRewind ])
    ,(177, group [       XK_XF86Phone ])
    ,(179, group [       XK_XF86Tools ])
    ,(180, group [    XK_XF86HomePage ])
    ,(181, group [      XK_XF86Reload ])
    ,(182, group [       XK_XF86Close ])
    ,(185, group [    XK_XF86ScrollUp ])
    ,(186, group [  XK_XF86ScrollDown ])
    ,(187, group [       XK_parenleft ])
    ,(188, group [      XK_parenright ])
    ,(189, group [         XK_XF86New ])
    ,(190, group [            XK_Redo ])
    ,(191, group [             XK_bar ])
    ,(192, group [       XK_parenleft ])
    ,(193, group [      XK_parenright ])
    ,(194, group [          XK_Insert ])
    ,(195, group [           XK_Alt_L,           XK_Alt_L ])
    ,(196, group [     XK_XF86Launch9 ])
    ,(198, group [ XK_XF86AudioMicMute ])
    ,(199, group [ XK_XF86TouchpadToggle ])
    ,(200, group [  XK_XF86TouchpadOn ])
    ,(201, group [ XK_XF86TouchpadOff ])
    ,(203, group [     XK_Mode_switch ])
    ,(204, group [        XK_NoSymbol,           XK_Alt_L ])
    ,(205, group [        XK_NoSymbol,          XK_Meta_L ])
    ,(206, group [        XK_NoSymbol,         XK_Super_L ])
    ,(207, group [        XK_NoSymbol,         XK_Hyper_L ])
    ,(208, group [   XK_XF86AudioPlay ])
    ,(209, group [  XK_XF86AudioPause ])
    ,(210, group [     XK_XF86Launch3 ])
    ,(211, group [     XK_XF86Launch4 ])
    ,(212, group [     XK_XF86LaunchB ])
    ,(213, group [     XK_XF86Suspend ])
    ,(214, group [       XK_XF86Close ])
    ,(215, group [   XK_XF86AudioPlay ])
    ,(216, group [ XK_XF86AudioForward ])
    ,(218, group [           XK_Print ])
    ,(220, group [      XK_XF86WebCam ])
    ,(223, group [        XK_XF86Mail ])
    ,(224, group [   XK_XF86Messenger ])
    ,(225, group [      XK_XF86Search ])
    ,(226, group [          XK_XF86Go ])
    ,(227, group [     XK_XF86Finance ])
    ,(228, group [        XK_XF86Game ])
    ,(229, group [        XK_XF86Shop ])
    ,(231, group [          XK_Cancel ])
    ,(232, group [ XK_XF86MonBrightnessDown ])
    ,(233, group [ XK_XF86MonBrightnessUp ])
    ,(234, group [  XK_XF86AudioMedia ])
    ,(235, group [     XK_XF86Display ])
    ,(236, group [ XK_XF86KbdLightOnOff ])
    ,(237, group [ XK_XF86KbdBrightnessDown ])
    ,(238, group [ XK_XF86KbdBrightnessUp ])
    ,(239, group [        XK_XF86Send ])
    ,(240, group [       XK_XF86Reply ])
    ,(241, group [ XK_XF86MailForward ])
    ,(242, group [        XK_XF86Save ])
    ,(243, group [   XK_XF86Documents ])
    ,(244, group [     XK_XF86Battery ])
    ,(245, group [   XK_XF86Bluetooth ])
    ,(246, group [        XK_XF86WLAN ])
]
