flags: {}
extra-package-dbs: []
packages:
- '.'
- location: /home/j/dev/apps/haskell/libraries/36-9ph
  extra-dep: true
- location: /home/j/dev/apps/haskell/libraries/11-bitmask
  extra-dep: true
- location: /home/j/dev/apps/haskell/libraries/37-9pserver
  extra-dep: true
extra-deps:
- NineP-0.0.2.4
- posix-paths-0.2.1.0
resolver: nightly-2016-10-14
