flags: {}
extra-package-dbs: []
packages:
- '.'
- location: /home/j/dev/apps/haskell/libraries/36-9ph
  extra-dep: true
- location: /home/j/dev/apps/haskell/libraries/11-bitmask
  extra-dep: true
- location: /home/j/dev/apps/haskell/libraries/37-9pserver
  extra-dep: true
resolver: nightly-2016-10-14
